### ISSUE TITLE
confusion about the code of softmax implementation

### ISSUE THREAD

**Issue by yaoqi-zd** [ascust/SEC-MXNet#10]
Hi, May I ask you questions about your implementation of softmax function?
in ./cores/symbols/SEC_syms.py, you implement softmax as follows:
```
def create_softmax(preds, min_prob=0.0001):
    min_prob_const = mx.sym.ones((1, 1, 1, 1)) * min_prob
    preds_max = mx.sym.max(preds, keepdims=True, axis=1, name="softmax_max")
    preds_exp = mx.sym.exp(mx.sym.broadcast_minus(preds, preds_max, name="softmax_minus"))
    tmp1 = mx.sym.sum(preds_exp, keepdims=True, axis=1)
    tmp2 = mx.sym.broadcast_div(preds_exp, tmp1)
    tmp3 = mx.sym.broadcast_add(tmp2, min_prob_const)
    probs = mx.sym.broadcast_div(tmp3, mx.sym.sum(tmp3, axis=1, keepdims=True))
    return probs
```

In my mind, the variable 'tmp2' is exactly the softmax output, why do you add another small value and normalize again?

**Comment by ascust** [comment]
@yaoqi-zd Hi again. I followed the original Caffe version as well on this. In the original one:
```
preds = T.ftensor4()
top_diff = T.ftensor4()

preds_max = T.addbroadcast(T.max(preds, axis=1, keepdims=True), 1)
preds_exp = np.exp(preds - preds_max)
probs = preds_exp / T.addbroadcast(T.sum(preds_exp, axis=1, keepdims=True), 1) + min_prob
probs = probs / T.sum(probs, axis=1, keepdims=True)

probs_sum = T.sum(probs * top_diff)
```
So my understanding is that, the renormalization with "min_prob" guarantees the probs has a minimum value instead of a near zero value. So This might avoid some numerical issues in terms of the later operations.

**Comment by yaoqi-zd** [comment]
@ascust I've seen the original one, thanks for your explanation
