### ISSUE TITLE
CRF layer usage seems incorrect

### ISSUE THREAD

**Issue by yaoqi-zd** [ascust/SEC-MXNet#11]
Sorry I'm new to MXNet, but the usage of your crf layer in SEC_vgg16.py and SEC_resnet50.py seems incorrect. I have looked into the CRF layer, it requires the input unary to be 'log(prob)' form, as indicated below:
```
def inference(self, im, unary):
	#im: image HxWx3
	#unary: CxHxW should be "log(p)". take log of probability

	H, W = im.shape[:2]
	C = unary.shape[0]
	d = dcrf.DenseCRF2D(W, H, C)
	d.setUnaryEnergy(-unary.reshape(C, -1))
```
however, in SEC_vgg16.py and SEC_resnet50.py, when you use the CRF layer, your input unary term seems not satisfy the requirement. for example, in SEC_vgg16.py
```
preds = create_classifier(body, class_num=class_num, workspace=workspace, lr_type="alex10")
probs = SEC_syms.create_softmax(preds)
crf = mx.symbol.Custom(data=preds, small_ims=small_ims, name='crf', op_type='crf_layer',
                           pos_xy_std=3, pos_w=3, bi_xy_std=80, bi_rgb_std=13, bi_w=10,
                            maxiter=10, scale_factor=12.0, min_prob=0.0001)
```
variable 'preds' is the predicted score map and I don't see you perform any futher transformations in 'crf_layer' before feeding it to inference function,

**Comment by ascust** [comment]
@yaoqi-zd Thanks for your interest. I think you are right. It is not accurate to define unary as log(p). Actually I follow the original Caffe implementation, which you can have a look here:
https://github.com/kolesman/SEC
In the original implementation, the CRF layer takes the output of the last conv layer as the input. This is later used as the unary part in CRF like:
```crf.set_unary_energy(-unary.ravel().astype('float32'))```
It is like it assumes "unary" is the log(p)

Could you compare the version with the Caffe one as well? Correct me if I said anything wrong.

**Comment by yaoqi-zd** [comment]
@ascust  yes, you'r right, the original implementation seems also use the probability rather than  log(prob), I've tried replacing "preds" with log(prob) but the performance doesn't change. Maybe both choices are ok
