### ISSUE TITLE
About the seeds

### ISSUE THREAD

**Issue by jsdd25** [ascust/SEC-MXNet#12]
@ascust Hello, your work is very amazing! I just want to segment humans and backgrounds, and I don't want to segment other objects on my own datasets. I have about 5000 images, 2500 of them contain humans, 2500 of them have no humans. However, in my dataset, the images contain humans are taken in the same indoor scene (scene A) and images without humans are taken in different indoor scenes (scene B, scene C, scene D ... ). None of the images without humans is taken in the scene A. Also, the images without humans may contains other objects, such as bottles, books, chairs, desks, etc. Can I generate accurate seeds to locate only human seeds as foreground in this case? Thank you very much!

**Comment by ascust** [comment]
Hi
It highly depends on the content of the images. If there are some objects always shown up with human, they might be treated as the regions of interest because of the co-occurance. I suggest you try the code and have a look at the code. You dont even have to run everything. Only the foreground and background cue parts are enough.

**Comment by jsdd25** [comment]
@ascust Thank you very much! The images contain humans are taken continuously by the camera in the same indoor scene. Therefore, it is destined to have some objects always shown up with human. But,  I can remove humans from the original images by using some techniques (of course, it is impossible to be very accurate at every pixel belonging to humans), then use them as new images and expand the entire data set. Can I generate accurate seeds to locate only human seeds as foreground in this way? Thank you very much!

**Comment by ascust** [comment]
I am not 100% sure. The insight behind the foreground cue generation is that the neural network will focus on the most discriminative regions. Therefore it is hard to tell whether the network will focus on the humans as we expected. It is better to give it a shot.
