### ISSUE TITLE
Model Training

### ISSUE THREAD

**Issue by karthik-sem** [ascust/SEC-MXNet#15]
U have used Segmentation classes for creating Augmented images.Will the Augmented images be used for training?If so aren't we using fully supervised data for training? Please let me know

**Comment by ascust** [comment]
Could you be more specific about "used Segmentation classes for creating Augmented images"? Which part of the code are you referring to?

**Comment by karthik-sem** [comment]
I referred to the SegmentationClasses of SBD dataset used in the file create_dataset.py

**Comment by ascust** [comment]
sorry for the late reply. The setting is basically that we include the augmented images as well as the original VOC images, which are 10, 582 images in total. We only use the image-level labels for training. There is no pixel-level mask involved.

**Comment by karthik-sem** [comment]
The augmented images which are used for training are pixel wise annotations isnt it?

**Comment by ascust** [comment]
they do provide the pixel-level masks. But in the weakly supervised setting, we only use the image-level labels.

**Comment by ascust** [comment]
they do provide the pixel-level masks. But in the weakly supervised setting, we only use the image-level labels.
