### ISSUE TITLE
no such file or directory: 'dataset/voc_multi_file.p'

### ISSUE THREAD

**Issue by XZNWU** [ascust/SEC-MXNet#5]
Hi, Thank you very much for sharing the code. There was an error while running: no such file or directory: 'dataset/voc_multi_file.p'， bg_cue_net-1.params， fg_cue_net-1.params. Can you share this file?

**Comment by ascust** [comment]
hi, did you follow the instructions? It seems you run some latter script without running the former ones first. "voc_multi_file.p" is the one storing the label info, which is created when you create the dataset using "create_dataset.py". "bg_cue_net-1.params" and "fg_cue_net-1.params" are the model files for foreground and background cues, which are created when you train the cues using "train_bg_cues.py" and "train_fg_cues.py".

**Comment by XZNWU** [comment]
Thank you very much
